### ISSUE TITLE
Serving static file

### ISSUE THREAD

**Issue by sul4bh** [andrewgodwin/channels-examples#1]
Do you think it would be a good idea to enable serving static file when running these examples with runworker? Even though its a bad practice, it will at least make it easier to run these examples.

I came across this discussion https://github.com/andrewgodwin/channels/issues/87 and a simple solution would be adding something like this: https://github.com/jacobian/channels-example/blob/master/chat/routing.py#L5-L8

**Comment by andrewgodwin** [comment]
They serve static files when using `runserver`, which I figured was a good enough start - I'm hoping that Whitenoise v3 will get released (which will be a middleware implementation that works with Channels) and then we can roll that in.
